"""empty message

Revision ID: 934c51fe62fc
Revises: 657293d876c0
Create Date: 2024-04-13 11:28:01.848134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934c51fe62fc'
down_revision = '657293d876c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
